# Generated by Django 3.2.12 on 2022-03-04 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projfile',
            name='author',
        ),
        migrations.RemoveField(
            model_name='projfile',
            name='project',
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='project',
        ),
        migrations.RemoveField(
            model_name='userproject',
            name='user',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjFile',
        ),
        migrations.DeleteModel(
            name='UserProject',
        ),
    ]
